version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "13306:3306"
    networks:
      - algafood-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=0
      - SERVICES=sqs,events,ses,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - algafood-network

  algafood-api:
    build: .
    image: algafood-api
    command: ["java", "-jar", "api.jar"] # Removido o wait-for-it
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
      AWS_ENDPOINT_URL: http://localstack:4566 # Aponta para o LocalStack
    networks:
      - algafood-network
    depends_on:
      algafood-mysql:
        condition: service_healthy # Espera o MySQL estar saud√°vel
      localstack:
        condition: service_started # Apenas espera o LocalStack iniciar

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
